module ModerationAPI
  module Models
    type account_list_params =
      {  } & ModerationAPI::Internal::Type::request_parameters

    class AccountListParams < ModerationAPI::Internal::Type::BaseModel
      extend ModerationAPI::Internal::Type::RequestParameters::Converter
      include ModerationAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: ModerationAPI::request_opts) -> void

      def to_hash: -> { request_options: ModerationAPI::RequestOptions }
    end
  end
end
