module ModerationAPI
  module Models
    type action_list_response_item =
      {
        id: String,
        built_in: bool?,
        created_at: String,
        filter_in_queue_ids: ::Array[String],
        free_text: bool,
        name: String,
        position: ModerationAPI::Models::ActionListResponseItem::position,
        possible_values: ::Array[ModerationAPI::Models::ActionListResponseItem::PossibleValue],
        queue_behaviour: ModerationAPI::Models::ActionListResponseItem::queue_behaviour,
        value_required: bool,
        webhooks: ::Array[ModerationAPI::Models::ActionListResponseItem::Webhook],
        description: String?,
        key: String?,
        type: ModerationAPI::Models::ActionListResponseItem::type_?
      }

    class ActionListResponseItem < ModerationAPI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor built_in: bool?

      attr_accessor created_at: String

      attr_accessor filter_in_queue_ids: ::Array[String]

      attr_accessor free_text: bool

      attr_accessor name: String

      attr_accessor position: ModerationAPI::Models::ActionListResponseItem::position

      attr_accessor possible_values: ::Array[ModerationAPI::Models::ActionListResponseItem::PossibleValue]

      attr_accessor queue_behaviour: ModerationAPI::Models::ActionListResponseItem::queue_behaviour

      attr_accessor value_required: bool

      attr_accessor webhooks: ::Array[ModerationAPI::Models::ActionListResponseItem::Webhook]

      attr_accessor description: String?

      attr_accessor key: String?

      attr_accessor type: ModerationAPI::Models::ActionListResponseItem::type_?

      def initialize: (
        id: String,
        built_in: bool?,
        created_at: String,
        filter_in_queue_ids: ::Array[String],
        free_text: bool,
        name: String,
        position: ModerationAPI::Models::ActionListResponseItem::position,
        possible_values: ::Array[ModerationAPI::Models::ActionListResponseItem::PossibleValue],
        queue_behaviour: ModerationAPI::Models::ActionListResponseItem::queue_behaviour,
        value_required: bool,
        webhooks: ::Array[ModerationAPI::Models::ActionListResponseItem::Webhook],
        ?description: String?,
        ?key: String?,
        ?type: ModerationAPI::Models::ActionListResponseItem::type_?
      ) -> void

      def to_hash: -> {
        id: String,
        built_in: bool?,
        created_at: String,
        filter_in_queue_ids: ::Array[String],
        free_text: bool,
        name: String,
        position: ModerationAPI::Models::ActionListResponseItem::position,
        possible_values: ::Array[ModerationAPI::Models::ActionListResponseItem::PossibleValue],
        queue_behaviour: ModerationAPI::Models::ActionListResponseItem::queue_behaviour,
        value_required: bool,
        webhooks: ::Array[ModerationAPI::Models::ActionListResponseItem::Webhook],
        description: String?,
        key: String?,
        type: ModerationAPI::Models::ActionListResponseItem::type_?
      }

      type position = :ALL_QUEUES | :SOME_QUEUES | :HIDDEN

      module Position
        extend ModerationAPI::Internal::Type::Enum

        ALL_QUEUES: :ALL_QUEUES
        SOME_QUEUES: :SOME_QUEUES
        HIDDEN: :HIDDEN

        def self?.values: -> ::Array[ModerationAPI::Models::ActionListResponseItem::position]
      end

      type possible_value = { value: String }

      class PossibleValue < ModerationAPI::Internal::Type::BaseModel
        attr_accessor value: String

        def initialize: (value: String) -> void

        def to_hash: -> { value: String }
      end

      type queue_behaviour = :REMOVE | :ADD | :NO_CHANGE

      module QueueBehaviour
        extend ModerationAPI::Internal::Type::Enum

        REMOVE: :REMOVE
        ADD: :ADD
        NO_CHANGE: :NO_CHANGE

        def self?.values: -> ::Array[ModerationAPI::Models::ActionListResponseItem::queue_behaviour]
      end

      type webhook =
        {
          id: String,
          name: String,
          url: String,
          description: String?,
          moderation_action_id: String?
        }

      class Webhook < ModerationAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_accessor url: String

        attr_accessor description: String?

        attr_accessor moderation_action_id: String?

        def initialize: (
          id: String,
          name: String,
          url: String,
          ?description: String?,
          ?moderation_action_id: String?
        ) -> void

        def to_hash: -> {
          id: String,
          name: String,
          url: String,
          description: String?,
          moderation_action_id: String?
        }
      end

      type type_ =
        :AUTHOR_BLOCK
        | :AUTHOR_BLOCK_TEMP
        | :AUTHOR_UNBLOCK
        | :AUTHOR_DELETE
        | :AUTHOR_REPORT
        | :AUTHOR_WARN
        | :AUTHOR_CUSTOM
        | :ITEM_CUSTOM

      module Type
        extend ModerationAPI::Internal::Type::Enum

        AUTHOR_BLOCK: :AUTHOR_BLOCK
        AUTHOR_BLOCK_TEMP: :AUTHOR_BLOCK_TEMP
        AUTHOR_UNBLOCK: :AUTHOR_UNBLOCK
        AUTHOR_DELETE: :AUTHOR_DELETE
        AUTHOR_REPORT: :AUTHOR_REPORT
        AUTHOR_WARN: :AUTHOR_WARN
        AUTHOR_CUSTOM: :AUTHOR_CUSTOM
        ITEM_CUSTOM: :ITEM_CUSTOM

        def self?.values: -> ::Array[ModerationAPI::Models::ActionListResponseItem::type_]
      end
    end

    type action_list_response =
      ::Array[ModerationAPI::Models::ActionListResponseItem]

    ActionListResponse: ModerationAPI::Internal::Type::Converter
  end
end
