module ModerationAPI
  module Models
    type content_submit_params =
      {
        content: ModerationAPI::Models::ContentSubmitParams::content,
        author_id: String,
        channel: String,
        content_id: String,
        conversation_id: String,
        do_not_store: bool,
        metadata: ::Hash[Symbol, top],
        meta_type: ModerationAPI::Models::ContentSubmitParams::meta_type,
        policies: ::Array[ModerationAPI::Models::ContentSubmitParams::policy],
        timestamp: Float
      }
      & ModerationAPI::Internal::Type::request_parameters

    class ContentSubmitParams < ModerationAPI::Internal::Type::BaseModel
      extend ModerationAPI::Internal::Type::RequestParameters::Converter
      include ModerationAPI::Internal::Type::RequestParameters

      attr_accessor content: ModerationAPI::Models::ContentSubmitParams::content

      attr_reader author_id: String?

      def author_id=: (String) -> String

      attr_reader channel: String?

      def channel=: (String) -> String

      attr_reader content_id: String?

      def content_id=: (String) -> String

      attr_reader conversation_id: String?

      def conversation_id=: (String) -> String

      attr_reader do_not_store: bool?

      def do_not_store=: (bool) -> bool

      attr_reader metadata: ::Hash[Symbol, top]?

      def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader meta_type: ModerationAPI::Models::ContentSubmitParams::meta_type?

      def meta_type=: (
        ModerationAPI::Models::ContentSubmitParams::meta_type
      ) -> ModerationAPI::Models::ContentSubmitParams::meta_type

      attr_reader policies: ::Array[ModerationAPI::Models::ContentSubmitParams::policy]?

      def policies=: (
        ::Array[ModerationAPI::Models::ContentSubmitParams::policy]
      ) -> ::Array[ModerationAPI::Models::ContentSubmitParams::policy]

      attr_reader timestamp: Float?

      def timestamp=: (Float) -> Float

      def initialize: (
        content: ModerationAPI::Models::ContentSubmitParams::content,
        ?author_id: String,
        ?channel: String,
        ?content_id: String,
        ?conversation_id: String,
        ?do_not_store: bool,
        ?metadata: ::Hash[Symbol, top],
        ?meta_type: ModerationAPI::Models::ContentSubmitParams::meta_type,
        ?policies: ::Array[ModerationAPI::Models::ContentSubmitParams::policy],
        ?timestamp: Float,
        ?request_options: ModerationAPI::request_opts
      ) -> void

      def to_hash: -> {
        content: ModerationAPI::Models::ContentSubmitParams::content,
        author_id: String,
        channel: String,
        content_id: String,
        conversation_id: String,
        do_not_store: bool,
        metadata: ::Hash[Symbol, top],
        meta_type: ModerationAPI::Models::ContentSubmitParams::meta_type,
        policies: ::Array[ModerationAPI::Models::ContentSubmitParams::policy],
        timestamp: Float,
        request_options: ModerationAPI::RequestOptions
      }

      type content =
        ModerationAPI::ContentSubmitParams::Content::Text
        | ModerationAPI::ContentSubmitParams::Content::Image
        | ModerationAPI::ContentSubmitParams::Content::Video
        | ModerationAPI::ContentSubmitParams::Content::Audio
        | ModerationAPI::ContentSubmitParams::Content::Object

      module Content
        extend ModerationAPI::Internal::Type::Union

        type text = { text: String, type: :text }

        class Text < ModerationAPI::Internal::Type::BaseModel
          attr_accessor text: String

          attr_accessor type: :text

          def initialize: (text: String, ?type: :text) -> void

          def to_hash: -> { text: String, type: :text }
        end

        type image = { type: :image, data: String, url: String }

        class Image < ModerationAPI::Internal::Type::BaseModel
          attr_accessor type: :image

          attr_reader data: String?

          def data=: (String) -> String

          attr_reader url: String?

          def url=: (String) -> String

          def initialize: (?data: String, ?url: String, ?type: :image) -> void

          def to_hash: -> { type: :image, data: String, url: String }
        end

        type video = { type: :video, url: String }

        class Video < ModerationAPI::Internal::Type::BaseModel
          attr_accessor type: :video

          attr_accessor url: String

          def initialize: (url: String, ?type: :video) -> void

          def to_hash: -> { type: :video, url: String }
        end

        type audio = { type: :audio, url: String }

        class Audio < ModerationAPI::Internal::Type::BaseModel
          attr_accessor type: :audio

          attr_accessor url: String

          def initialize: (url: String, ?type: :audio) -> void

          def to_hash: -> { type: :audio, url: String }
        end

        type object =
          {
            data: ::Hash[Symbol, ModerationAPI::Models::ContentSubmitParams::Content::Object::data],
            type: :object
          }

        class Object < ModerationAPI::Internal::Type::BaseModel
          attr_accessor data: ::Hash[Symbol, ModerationAPI::Models::ContentSubmitParams::Content::Object::data]

          attr_accessor type: :object

          def initialize: (
            data: ::Hash[Symbol, ModerationAPI::Models::ContentSubmitParams::Content::Object::data],
            ?type: :object
          ) -> void

          def to_hash: -> {
            data: ::Hash[Symbol, ModerationAPI::Models::ContentSubmitParams::Content::Object::data],
            type: :object
          }

          type data =
            ModerationAPI::ContentSubmitParams::Content::Object::Data::Text
            | ModerationAPI::ContentSubmitParams::Content::Object::Data::Image
            | ModerationAPI::ContentSubmitParams::Content::Object::Data::Video
            | ModerationAPI::ContentSubmitParams::Content::Object::Data::Audio

          module Data
            extend ModerationAPI::Internal::Type::Union

            type text = { text: String, type: :text }

            class Text < ModerationAPI::Internal::Type::BaseModel
              attr_accessor text: String

              attr_accessor type: :text

              def initialize: (text: String, ?type: :text) -> void

              def to_hash: -> { text: String, type: :text }
            end

            type image = { type: :image, data: String, url: String }

            class Image < ModerationAPI::Internal::Type::BaseModel
              attr_accessor type: :image

              attr_reader data: String?

              def data=: (String) -> String

              attr_reader url: String?

              def url=: (String) -> String

              def initialize: (
                ?data: String,
                ?url: String,
                ?type: :image
              ) -> void

              def to_hash: -> { type: :image, data: String, url: String }
            end

            type video = { type: :video, url: String }

            class Video < ModerationAPI::Internal::Type::BaseModel
              attr_accessor type: :video

              attr_accessor url: String

              def initialize: (url: String, ?type: :video) -> void

              def to_hash: -> { type: :video, url: String }
            end

            type audio = { type: :audio, url: String }

            class Audio < ModerationAPI::Internal::Type::BaseModel
              attr_accessor type: :audio

              attr_accessor url: String

              def initialize: (url: String, ?type: :audio) -> void

              def to_hash: -> { type: :audio, url: String }
            end

            def self?.variants: -> ::Array[ModerationAPI::Models::ContentSubmitParams::Content::Object::data]
          end
        end

        def self?.variants: -> ::Array[ModerationAPI::Models::ContentSubmitParams::content]
      end

      type meta_type =
        :profile
        | :message
        | :post
        | :comment
        | :event
        | :product
        | :review
        | :other

      module MetaType
        extend ModerationAPI::Internal::Type::Enum

        PROFILE: :profile
        MESSAGE: :message
        POST: :post
        COMMENT: :comment
        EVENT: :event
        PRODUCT: :product
        REVIEW: :review
        OTHER: :other

        def self?.values: -> ::Array[ModerationAPI::Models::ContentSubmitParams::meta_type]
      end

      type policy =
        ModerationAPI::ContentSubmitParams::Policy::Toxicity
        | ModerationAPI::ContentSubmitParams::Policy::PersonalInformation
        | ModerationAPI::ContentSubmitParams::Policy::ToxicitySevere
        | ModerationAPI::ContentSubmitParams::Policy::Hate
        | ModerationAPI::ContentSubmitParams::Policy::Illicit
        | ModerationAPI::ContentSubmitParams::Policy::IllicitDrugs
        | ModerationAPI::ContentSubmitParams::Policy::IllicitAlcohol
        | ModerationAPI::ContentSubmitParams::Policy::IllicitFirearms
        | ModerationAPI::ContentSubmitParams::Policy::IllicitTobacco
        | ModerationAPI::ContentSubmitParams::Policy::IllicitGambling
        | ModerationAPI::ContentSubmitParams::Policy::Cannabis
        | ModerationAPI::ContentSubmitParams::Policy::Adult
        | ModerationAPI::ContentSubmitParams::Policy::Crypto
        | ModerationAPI::ContentSubmitParams::Policy::Sexual
        | ModerationAPI::ContentSubmitParams::Policy::Flirtation
        | ModerationAPI::ContentSubmitParams::Policy::Profanity
        | ModerationAPI::ContentSubmitParams::Policy::Violence
        | ModerationAPI::ContentSubmitParams::Policy::SelfHarm
        | ModerationAPI::ContentSubmitParams::Policy::Spam
        | ModerationAPI::ContentSubmitParams::Policy::SelfPromotion
        | ModerationAPI::ContentSubmitParams::Policy::Political
        | ModerationAPI::ContentSubmitParams::Policy::Religion
        | ModerationAPI::ContentSubmitParams::Policy::CodeAbuse
        | ModerationAPI::ContentSubmitParams::Policy::PiiMasking
        | ModerationAPI::ContentSubmitParams::Policy::URLMasking
        | ModerationAPI::ContentSubmitParams::Policy::Guideline

      module Policy
        extend ModerationAPI::Internal::Type::Union

        type toxicity = { id: :toxicity, flag: bool, threshold: Float }

        class Toxicity < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :toxicity

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :toxicity
          ) -> void

          def to_hash: -> { id: :toxicity, flag: bool, threshold: Float }
        end

        type personal_information =
          { id: :personal_information, flag: bool, threshold: Float }

        class PersonalInformation < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :personal_information

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :personal_information
          ) -> void

          def to_hash: -> {
            id: :personal_information,
            flag: bool,
            threshold: Float
          }
        end

        type toxicity_severe =
          { id: :toxicity_severe, flag: bool, threshold: Float }

        class ToxicitySevere < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :toxicity_severe

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :toxicity_severe
          ) -> void

          def to_hash: -> { id: :toxicity_severe, flag: bool, threshold: Float }
        end

        type hate = { id: :hate, flag: bool, threshold: Float }

        class Hate < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :hate

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :hate) -> void

          def to_hash: -> { id: :hate, flag: bool, threshold: Float }
        end

        type illicit = { id: :illicit, flag: bool, threshold: Float }

        class Illicit < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :illicit) -> void

          def to_hash: -> { id: :illicit, flag: bool, threshold: Float }
        end

        type illicit_drugs =
          { id: :illicit_drugs, flag: bool, threshold: Float }

        class IllicitDrugs < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit_drugs

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :illicit_drugs
          ) -> void

          def to_hash: -> { id: :illicit_drugs, flag: bool, threshold: Float }
        end

        type illicit_alcohol =
          { id: :illicit_alcohol, flag: bool, threshold: Float }

        class IllicitAlcohol < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit_alcohol

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :illicit_alcohol
          ) -> void

          def to_hash: -> { id: :illicit_alcohol, flag: bool, threshold: Float }
        end

        type illicit_firearms =
          { id: :illicit_firearms, flag: bool, threshold: Float }

        class IllicitFirearms < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit_firearms

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :illicit_firearms
          ) -> void

          def to_hash: -> {
            id: :illicit_firearms,
            flag: bool,
            threshold: Float
          }
        end

        type illicit_tobacco =
          { id: :illicit_tobacco, flag: bool, threshold: Float }

        class IllicitTobacco < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit_tobacco

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :illicit_tobacco
          ) -> void

          def to_hash: -> { id: :illicit_tobacco, flag: bool, threshold: Float }
        end

        type illicit_gambling =
          { id: :illicit_gambling, flag: bool, threshold: Float }

        class IllicitGambling < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :illicit_gambling

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :illicit_gambling
          ) -> void

          def to_hash: -> {
            id: :illicit_gambling,
            flag: bool,
            threshold: Float
          }
        end

        type cannabis = { id: :cannabis, flag: bool, threshold: Float }

        class Cannabis < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :cannabis

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :cannabis
          ) -> void

          def to_hash: -> { id: :cannabis, flag: bool, threshold: Float }
        end

        type adult = { id: :adult, flag: bool, threshold: Float }

        class Adult < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :adult

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :adult) -> void

          def to_hash: -> { id: :adult, flag: bool, threshold: Float }
        end

        type crypto = { id: :crypto, flag: bool, threshold: Float }

        class Crypto < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :crypto

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :crypto) -> void

          def to_hash: -> { id: :crypto, flag: bool, threshold: Float }
        end

        type sexual = { id: :sexual, flag: bool, threshold: Float }

        class Sexual < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :sexual

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :sexual) -> void

          def to_hash: -> { id: :sexual, flag: bool, threshold: Float }
        end

        type flirtation = { id: :flirtation, flag: bool, threshold: Float }

        class Flirtation < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :flirtation

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :flirtation
          ) -> void

          def to_hash: -> { id: :flirtation, flag: bool, threshold: Float }
        end

        type profanity = { id: :profanity, flag: bool, threshold: Float }

        class Profanity < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :profanity

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :profanity
          ) -> void

          def to_hash: -> { id: :profanity, flag: bool, threshold: Float }
        end

        type violence = { id: :violence, flag: bool, threshold: Float }

        class Violence < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :violence

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :violence
          ) -> void

          def to_hash: -> { id: :violence, flag: bool, threshold: Float }
        end

        type self_harm = { id: :self_harm, flag: bool, threshold: Float }

        class SelfHarm < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :self_harm

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :self_harm
          ) -> void

          def to_hash: -> { id: :self_harm, flag: bool, threshold: Float }
        end

        type spam = { id: :spam, flag: bool, threshold: Float }

        class Spam < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :spam

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (flag: bool, ?threshold: Float, ?id: :spam) -> void

          def to_hash: -> { id: :spam, flag: bool, threshold: Float }
        end

        type self_promotion =
          { id: :self_promotion, flag: bool, threshold: Float }

        class SelfPromotion < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :self_promotion

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :self_promotion
          ) -> void

          def to_hash: -> { id: :self_promotion, flag: bool, threshold: Float }
        end

        type political = { id: :political, flag: bool, threshold: Float }

        class Political < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :political

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :political
          ) -> void

          def to_hash: -> { id: :political, flag: bool, threshold: Float }
        end

        type religion = { id: :religion, flag: bool, threshold: Float }

        class Religion < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :religion

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :religion
          ) -> void

          def to_hash: -> { id: :religion, flag: bool, threshold: Float }
        end

        type code_abuse = { id: :code_abuse, flag: bool, threshold: Float }

        class CodeAbuse < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :code_abuse

          attr_accessor flag: bool

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            ?threshold: Float,
            ?id: :code_abuse
          ) -> void

          def to_hash: -> { id: :code_abuse, flag: bool, threshold: Float }
        end

        type pii_masking =
          {
            id: :pii,
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::PiiMasking::Entity]
          }

        class PiiMasking < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :pii

          attr_accessor entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::PiiMasking::Entity]

          def initialize: (
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::PiiMasking::Entity],
            ?id: :pii
          ) -> void

          def to_hash: -> {
            id: :pii,
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::PiiMasking::Entity]
          }

          type entity =
            { enable: bool, flag: bool, mask: String, should_mask: bool }

          class Entity < ModerationAPI::Internal::Type::BaseModel
            attr_reader enable: bool?

            def enable=: (bool) -> bool

            attr_reader flag: bool?

            def flag=: (bool) -> bool

            attr_reader mask: String?

            def mask=: (String) -> String

            attr_reader should_mask: bool?

            def should_mask=: (bool) -> bool

            def initialize: (
              ?enable: bool,
              ?flag: bool,
              ?mask: String,
              ?should_mask: bool
            ) -> void

            def to_hash: -> {
              enable: bool,
              flag: bool,
              mask: String,
              should_mask: bool
            }
          end
        end

        type url_masking =
          {
            id: :url,
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::URLMasking::Entity]
          }

        class URLMasking < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :url

          attr_accessor entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::URLMasking::Entity]

          def initialize: (
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::URLMasking::Entity],
            ?id: :url
          ) -> void

          def to_hash: -> {
            id: :url,
            entities: ::Hash[Symbol, ModerationAPI::ContentSubmitParams::Policy::URLMasking::Entity]
          }

          type entity =
            { enable: bool, flag: bool, mask: String, should_mask: bool }

          class Entity < ModerationAPI::Internal::Type::BaseModel
            attr_reader enable: bool?

            def enable=: (bool) -> bool

            attr_reader flag: bool?

            def flag=: (bool) -> bool

            attr_reader mask: String?

            def mask=: (String) -> String

            attr_reader should_mask: bool?

            def should_mask=: (bool) -> bool

            def initialize: (
              ?enable: bool,
              ?flag: bool,
              ?mask: String,
              ?should_mask: bool
            ) -> void

            def to_hash: -> {
              enable: bool,
              flag: bool,
              mask: String,
              should_mask: bool
            }
          end
        end

        type guideline =
          {
            id: :guideline,
            flag: bool,
            guideline_key: String,
            instructions: String,
            threshold: Float
          }

        class Guideline < ModerationAPI::Internal::Type::BaseModel
          attr_accessor id: :guideline

          attr_accessor flag: bool

          attr_accessor guideline_key: String

          attr_accessor instructions: String

          attr_reader threshold: Float?

          def threshold=: (Float) -> Float

          def initialize: (
            flag: bool,
            guideline_key: String,
            instructions: String,
            ?threshold: Float,
            ?id: :guideline
          ) -> void

          def to_hash: -> {
            id: :guideline,
            flag: bool,
            guideline_key: String,
            instructions: String,
            threshold: Float
          }
        end

        def self?.variants: -> ::Array[ModerationAPI::Models::ContentSubmitParams::policy]
      end
    end
  end
end
