module ModerationAPI
  module Models
    type moderate_analyze_object_params =
      {
        value: ModerationAPI::ModerateAnalyzeObjectParams::Value,
        author_id: String,
        channel_key: String,
        content_id: String,
        context_id: String,
        do_not_store: bool,
        metadata: ::Hash[Symbol, top]
      }
      & ModerationAPI::Internal::Type::request_parameters

    class ModerateAnalyzeObjectParams < ModerationAPI::Internal::Type::BaseModel
      extend ModerationAPI::Internal::Type::RequestParameters::Converter
      include ModerationAPI::Internal::Type::RequestParameters

      attr_accessor value: ModerationAPI::ModerateAnalyzeObjectParams::Value

      attr_reader author_id: String?

      def author_id=: (String) -> String

      attr_reader channel_key: String?

      def channel_key=: (String) -> String

      attr_reader content_id: String?

      def content_id=: (String) -> String

      attr_reader context_id: String?

      def context_id=: (String) -> String

      attr_reader do_not_store: bool?

      def do_not_store=: (bool) -> bool

      attr_reader metadata: ::Hash[Symbol, top]?

      def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        value: ModerationAPI::ModerateAnalyzeObjectParams::Value,
        ?author_id: String,
        ?channel_key: String,
        ?content_id: String,
        ?context_id: String,
        ?do_not_store: bool,
        ?metadata: ::Hash[Symbol, top],
        ?request_options: ModerationAPI::request_opts
      ) -> void

      def to_hash: -> {
        value: ModerationAPI::ModerateAnalyzeObjectParams::Value,
        author_id: String,
        channel_key: String,
        content_id: String,
        context_id: String,
        do_not_store: bool,
        metadata: ::Hash[Symbol, top],
        request_options: ModerationAPI::RequestOptions
      }

      type value =
        {
          data: ::Hash[Symbol, ModerationAPI::ModerateAnalyzeObjectParams::Value::Data],
          type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::type_
        }

      class Value < ModerationAPI::Internal::Type::BaseModel
        attr_accessor data: ::Hash[Symbol, ModerationAPI::ModerateAnalyzeObjectParams::Value::Data]

        attr_accessor type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::type_

        def initialize: (
          data: ::Hash[Symbol, ModerationAPI::ModerateAnalyzeObjectParams::Value::Data],
          type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::type_
        ) -> void

        def to_hash: -> {
          data: ::Hash[Symbol, ModerationAPI::ModerateAnalyzeObjectParams::Value::Data],
          type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::type_
        }

        type data =
          {
            type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::Data::type_,
            value: String,
            model_ids: ::Array[String]
          }

        class Data < ModerationAPI::Internal::Type::BaseModel
          attr_accessor type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::Data::type_

          attr_accessor value: String

          attr_reader model_ids: ::Array[String]?

          def model_ids=: (::Array[String]) -> ::Array[String]

          def initialize: (
            type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::Data::type_,
            value: String,
            ?model_ids: ::Array[String]
          ) -> void

          def to_hash: -> {
            type: ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::Data::type_,
            value: String,
            model_ids: ::Array[String]
          }

          type type_ = :text | :image | :video | :audio

          module Type
            extend ModerationAPI::Internal::Type::Enum

            TEXT: :text
            IMAGE: :image
            VIDEO: :video
            AUDIO: :audio

            def self?.values: -> ::Array[ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::Data::type_]
          end
        end

        type type_ = :profile | :event | :product | :object

        module Type
          extend ModerationAPI::Internal::Type::Enum

          PROFILE: :profile
          EVENT: :event
          PRODUCT: :product
          OBJECT: :object

          def self?.values: -> ::Array[ModerationAPI::Models::ModerateAnalyzeObjectParams::Value::type_]
        end
      end
    end
  end
end
