module ModerationAPI
  module Models
    type moderate_analyze_image_response =
      {
        author: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author?,
        flagged: bool,
        labels: ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Label],
        request: ModerationAPI::Models::ModerateAnalyzeImageResponse::Request,
        status: String,
        content_id: String,
        error: top,
        texts: ::Array[String]
      }

    class ModerateAnalyzeImageResponse < ModerationAPI::Internal::Type::BaseModel
      attr_accessor author: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author?

      attr_accessor flagged: bool

      attr_accessor labels: ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Label]

      attr_accessor request: ModerationAPI::Models::ModerateAnalyzeImageResponse::Request

      attr_accessor status: String

      attr_reader content_id: String?

      def content_id=: (String) -> String

      attr_reader error: top?

      def error=: (top) -> top

      attr_reader texts: ::Array[String]?

      def texts=: (::Array[String]) -> ::Array[String]

      def initialize: (
        author: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author?,
        flagged: bool,
        labels: ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Label],
        request: ModerationAPI::Models::ModerateAnalyzeImageResponse::Request,
        status: String,
        ?content_id: String,
        ?error: top,
        ?texts: ::Array[String]
      ) -> void

      def to_hash: -> {
        author: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author?,
        flagged: bool,
        labels: ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Label],
        request: ModerationAPI::Models::ModerateAnalyzeImageResponse::Request,
        status: String,
        content_id: String,
        error: top,
        texts: ::Array[String]
      }

      type author =
        {
          id: String,
          block: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::Block?,
          status: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::status,
          trust_level: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::TrustLevel,
          external_id: String?
        }

      class Author < ModerationAPI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor block: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::Block?

        attr_accessor status: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::status

        attr_accessor trust_level: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::TrustLevel

        attr_accessor external_id: String?

        def initialize: (
          id: String,
          block: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::Block?,
          status: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::status,
          trust_level: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::TrustLevel,
          ?external_id: String?
        ) -> void

        def to_hash: -> {
          id: String,
          block: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::Block?,
          status: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::status,
          trust_level: ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::TrustLevel,
          external_id: String?
        }

        type block = { reason: String?, until_: Float? }

        class Block < ModerationAPI::Internal::Type::BaseModel
          attr_accessor reason: String?

          attr_accessor until_: Float?

          def initialize: (?reason: String?, ?until_: Float?) -> void

          def to_hash: -> { reason: String?, until_: Float? }
        end

        type status = :enabled | :suspended | :blocked

        module Status
          extend ModerationAPI::Internal::Type::Enum

          ENABLED: :enabled
          SUSPENDED: :suspended
          BLOCKED: :blocked

          def self?.values: -> ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Author::status]
        end

        type trust_level = { level: Float, manual: bool }

        class TrustLevel < ModerationAPI::Internal::Type::BaseModel
          attr_accessor level: Float

          attr_accessor manual: bool

          def initialize: (level: Float, manual: bool) -> void

          def to_hash: -> { level: Float, manual: bool }
        end
      end

      type label =
        {
          label: ModerationAPI::Models::ModerateAnalyzeImageResponse::Label::label,
          score: Float
        }

      class Label < ModerationAPI::Internal::Type::BaseModel
        attr_accessor label: ModerationAPI::Models::ModerateAnalyzeImageResponse::Label::label

        attr_accessor score: Float

        def initialize: (
          label: ModerationAPI::Models::ModerateAnalyzeImageResponse::Label::label,
          score: Float
        ) -> void

        def to_hash: -> {
          label: ModerationAPI::Models::ModerateAnalyzeImageResponse::Label::label,
          score: Float
        }

        type label =
          :nudity
          | :suggestive
          | :gore
          | :hate
          | :violence
          | :weapon
          | :smoking
          | :drugs
          | :alcohol
          | :text
          | :toxic

        module Label
          extend ModerationAPI::Internal::Type::Enum

          NUDITY: :nudity
          SUGGESTIVE: :suggestive
          GORE: :gore
          HATE: :hate
          VIOLENCE: :violence
          WEAPON: :weapon
          SMOKING: :smoking
          DRUGS: :drugs
          ALCOHOL: :alcohol
          TEXT: :text
          TOXIC: :toxic

          def self?.values: -> ::Array[ModerationAPI::Models::ModerateAnalyzeImageResponse::Label::label]
        end
      end

      type request = { quota_usage: Float, timestamp: Float }

      class Request < ModerationAPI::Internal::Type::BaseModel
        attr_accessor quota_usage: Float

        attr_accessor timestamp: Float

        def initialize: (quota_usage: Float, timestamp: Float) -> void

        def to_hash: -> { quota_usage: Float, timestamp: Float }
      end
    end
  end
end
