module ModerationAPI
  module Models
    type webhook_secret_retrieve_response = { secret: String }

    class WebhookSecretRetrieveResponse < ModerationAPI::Internal::Type::BaseModel
      attr_accessor secret: String

      def initialize: (secret: String) -> void

      def to_hash: -> { secret: String }
    end
  end
end
