module ModerationAPI
  module Models
    type wordlist_update_params =
      {
        description: String,
        key: String,
        name: String,
        strict: bool,
        words: ::Array[String]
      }
      & ModerationAPI::Internal::Type::request_parameters

    class WordlistUpdateParams < ModerationAPI::Internal::Type::BaseModel
      extend ModerationAPI::Internal::Type::RequestParameters::Converter
      include ModerationAPI::Internal::Type::RequestParameters

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader key: String?

      def key=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader strict: bool?

      def strict=: (bool) -> bool

      attr_reader words: ::Array[String]?

      def words=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?description: String,
        ?key: String,
        ?name: String,
        ?strict: bool,
        ?words: ::Array[String],
        ?request_options: ModerationAPI::request_opts
      ) -> void

      def to_hash: -> {
        description: String,
        key: String,
        name: String,
        strict: bool,
        words: ::Array[String],
        request_options: ModerationAPI::RequestOptions
      }
    end
  end
end
