module ModerationAPI
  module Models
    module Queue
      type item_unresolve_response =
        { status: String, success: bool, unresolved_at: String }

      class ItemUnresolveResponse < ModerationAPI::Internal::Type::BaseModel
        attr_accessor status: String

        attr_accessor success: bool

        attr_accessor unresolved_at: String

        def initialize: (
          status: String,
          success: bool,
          unresolved_at: String
        ) -> void

        def to_hash: -> { status: String, success: bool, unresolved_at: String }
      end
    end
  end
end
