# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "moderation_api/version"
require_relative "moderation_api/internal/util"
require_relative "moderation_api/internal/type/converter"
require_relative "moderation_api/internal/type/unknown"
require_relative "moderation_api/internal/type/boolean"
require_relative "moderation_api/internal/type/file_input"
require_relative "moderation_api/internal/type/enum"
require_relative "moderation_api/internal/type/union"
require_relative "moderation_api/internal/type/array_of"
require_relative "moderation_api/internal/type/hash_of"
require_relative "moderation_api/internal/type/base_model"
require_relative "moderation_api/internal/type/base_page"
require_relative "moderation_api/internal/type/request_parameters"
require_relative "moderation_api/internal"
require_relative "moderation_api/request_options"
require_relative "moderation_api/file_part"
require_relative "moderation_api/errors"
require_relative "moderation_api/internal/transport/base_client"
require_relative "moderation_api/internal/transport/pooled_net_requester"
require_relative "moderation_api/client"
require_relative "moderation_api/models/account_list_params"
require_relative "moderation_api/models/account_list_response"
require_relative "moderation_api/models/action_create_params"
require_relative "moderation_api/models/action_create_response"
require_relative "moderation_api/models/action_delete_params"
require_relative "moderation_api/models/action_delete_response"
require_relative "moderation_api/models/action_list_params"
require_relative "moderation_api/models/action_list_response"
require_relative "moderation_api/models/action_retrieve_params"
require_relative "moderation_api/models/action_retrieve_response"
require_relative "moderation_api/models/actions/execute_execute_by_id_params"
require_relative "moderation_api/models/actions/execute_execute_by_id_response"
require_relative "moderation_api/models/actions/execute_execute_params"
require_relative "moderation_api/models/actions/execute_execute_response"
require_relative "moderation_api/models/action_update_params"
require_relative "moderation_api/models/action_update_response"
require_relative "moderation_api/models/auth_create_params"
require_relative "moderation_api/models/auth_create_response"
require_relative "moderation_api/models/author_create_params"
require_relative "moderation_api/models/author_create_response"
require_relative "moderation_api/models/author_delete_params"
require_relative "moderation_api/models/author_delete_response"
require_relative "moderation_api/models/author_list_params"
require_relative "moderation_api/models/author_list_response"
require_relative "moderation_api/models/author_retrieve_params"
require_relative "moderation_api/models/author_retrieve_response"
require_relative "moderation_api/models/author_update_params"
require_relative "moderation_api/models/author_update_response"
require_relative "moderation_api/models/auth_retrieve_params"
require_relative "moderation_api/models/auth_retrieve_response"
require_relative "moderation_api/models/content_submit_params"
require_relative "moderation_api/models/content_submit_response"
require_relative "moderation_api/models/queue/item_list_params"
require_relative "moderation_api/models/queue/item_list_response"
require_relative "moderation_api/models/queue/item_resolve_params"
require_relative "moderation_api/models/queue/item_resolve_response"
require_relative "moderation_api/models/queue/item_unresolve_params"
require_relative "moderation_api/models/queue/item_unresolve_response"
require_relative "moderation_api/models/queue_get_stats_params"
require_relative "moderation_api/models/queue_get_stats_response"
require_relative "moderation_api/models/queue_retrieve_params"
require_relative "moderation_api/models/queue_retrieve_response"
require_relative "moderation_api/models/wordlist/word_add_params"
require_relative "moderation_api/models/wordlist/word_add_response"
require_relative "moderation_api/models/wordlist/word_remove_params"
require_relative "moderation_api/models/wordlist/word_remove_response"
require_relative "moderation_api/models/wordlist_get_embedding_status_params"
require_relative "moderation_api/models/wordlist_get_embedding_status_response"
require_relative "moderation_api/models/wordlist_list_params"
require_relative "moderation_api/models/wordlist_list_response"
require_relative "moderation_api/models/wordlist_retrieve_params"
require_relative "moderation_api/models/wordlist_retrieve_response"
require_relative "moderation_api/models/wordlist_update_params"
require_relative "moderation_api/models/wordlist_update_response"
require_relative "moderation_api/models"
require_relative "moderation_api/resources/account"
require_relative "moderation_api/resources/actions"
require_relative "moderation_api/resources/actions/execute"
require_relative "moderation_api/resources/auth"
require_relative "moderation_api/resources/authors"
require_relative "moderation_api/resources/content"
require_relative "moderation_api/resources/queue"
require_relative "moderation_api/resources/queue/items"
require_relative "moderation_api/resources/wordlist"
require_relative "moderation_api/resources/wordlist/words"
