module ModerationAPI
  module Resources
    class Content
      def submit: (
        content: ModerationAPI::Models::ContentSubmitParams::content,
        ?author_id: String,
        ?channel: String,
        ?content_id: String,
        ?conversation_id: String,
        ?do_not_store: bool,
        ?metadata: ::Hash[Symbol, top],
        ?meta_type: ModerationAPI::Models::ContentSubmitParams::meta_type,
        ?policies: ::Array[ModerationAPI::Models::ContentSubmitParams::policy],
        ?timestamp: Float,
        ?request_options: ModerationAPI::request_opts
      ) -> ModerationAPI::Models::ContentSubmitResponse

      def initialize: (client: ModerationAPI::Client) -> void
    end
  end
end
