module ModerationAPI
  module Resources
    class Moderate
      def analyze: (
        content: ModerationAPI::Models::ModerateAnalyzeParams::content,
        ?author_id: String,
        ?channel: String,
        ?content_id: String,
        ?conversation_id: String,
        ?do_not_store: bool,
        ?metadata: ::Hash[Symbol, top],
        ?meta_type: ModerationAPI::Models::ModerateAnalyzeParams::meta_type,
        ?request_options: ModerationAPI::request_opts
      ) -> ModerationAPI::Models::ModerateAnalyzeResponse

      def initialize: (client: ModerationAPI::Client) -> void
    end
  end
end
