module ModerationAPI
  module Resources
    class WebhookSecret
      def retrieve: (
        ?request_options: ModerationAPI::request_opts
      ) -> ModerationAPI::Models::WebhookSecretRetrieveResponse

      def initialize: (client: ModerationAPI::Client) -> void
    end
  end
end
